project:
  type: website

website:
  title: "Service de Plongée Scientifique"
  favicon: "assets/images/SPS_rlogo_final_RVB.jpg"
  image: "assets/images/SPS_rlogo_final_RVB.jpg"
  page-navigation: true
  open-graph: true
  repo-url: https://github.com/service-plongee-scientifique/service-plongee-scientifique.github.io
  repo-actions: [source, issue]
  navbar:
    logo: "assets/images/SPS_rlogo_final_RVB.jpg"
    right:
      - href: index.qmd
        text: " "
        icon: house-door-fill
      - href: presentation/index.qmd
        text: "Qui sommes nous?"
      - href: missions/index.qmd
        text: "Nos missions"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



