project:
  type: website

website:
  title: "service-plongee-scientifique.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



